/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BULLETIN_BOARD_H
#define BULLETIN_BOARD_H

#include "idl_types.h"

/* BulletinBoard service interface */
typedef struct _BulletinBoardIf BulletinBoardIf;  /* dummy object */

struct _BulletinBoardIfInterface
{
  GTypeInterface parent;

  gboolean (*add) (BulletinBoardIf *iface, const Message * msg, GError **error);
  gboolean (*get) (BulletinBoardIf *iface, GPtrArray ** _return, GError **error);
};
typedef struct _BulletinBoardIfInterface BulletinBoardIfInterface;

GType bulletin_board_if_get_type (void);
#define TYPE_BULLETIN_BOARD_IF (bulletin_board_if_get_type())
#define BULLETIN_BOARD_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BULLETIN_BOARD_IF, BulletinBoardIf))
#define IS_BULLETIN_BOARD_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BULLETIN_BOARD_IF))
#define BULLETIN_BOARD_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), TYPE_BULLETIN_BOARD_IF, BulletinBoardIfInterface))

gboolean bulletin_board_if_add (BulletinBoardIf *iface, const Message * msg, GError **error);
gboolean bulletin_board_if_get (BulletinBoardIf *iface, GPtrArray ** _return, GError **error);

/* BulletinBoard service client */
struct _BulletinBoardClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _BulletinBoardClient BulletinBoardClient;

struct _BulletinBoardClientClass
{
  GObjectClass parent;
};
typedef struct _BulletinBoardClientClass BulletinBoardClientClass;

GType bulletin_board_client_get_type (void);
#define TYPE_BULLETIN_BOARD_CLIENT (bulletin_board_client_get_type())
#define BULLETIN_BOARD_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BULLETIN_BOARD_CLIENT, BulletinBoardClient))
#define BULLETIN_BOARD_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_BULLETIN_BOARD_CLIENT, BulletinBoardClientClass))
#define BULLETIN_BOARD_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BULLETIN_BOARD_CLIENT))
#define BULLETIN_BOARD_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_BULLETIN_BOARD_CLIENT))
#define BULLETIN_BOARD_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BULLETIN_BOARD_CLIENT, BulletinBoardClientClass))

gboolean bulletin_board_client_add (BulletinBoardIf * iface, const Message * msg, GError ** error);
gboolean bulletin_board_client_send_add (BulletinBoardIf * iface, const Message * msg, GError ** error);
gboolean bulletin_board_client_recv_add (BulletinBoardIf * iface, GError ** error);
gboolean bulletin_board_client_get (BulletinBoardIf * iface, GPtrArray ** _return, GError ** error);
gboolean bulletin_board_client_send_get (BulletinBoardIf * iface, GError ** error);
gboolean bulletin_board_client_recv_get (BulletinBoardIf * iface, GPtrArray ** _return, GError ** error);
void bulletin_board_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
void bulletin_board_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);

#endif /* BULLETIN_BOARD_H */
