/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IDL_TYPES_H
#define IDL_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>

/* custom thrift includes */

/* begin types */

/* struct Message */
struct _Message
{ 
  ThriftStruct parent; 

  /* public */
  gchar * text;
  gboolean __isset_text;
  gchar * date;
  gboolean __isset_date;
};
typedef struct _Message Message;

struct _MessageClass
{
  ThriftStructClass parent;
};
typedef struct _MessageClass MessageClass;

GType message_get_type (void);
#define TYPE_MESSAGE (message_get_type())
#define MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MESSAGE, Message))
#define MESSAGE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_MESSAGE, MessageClass))
#define IS_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MESSAGE))
#define IS_MESSAGE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_MESSAGE))
#define MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MESSAGE, MessageClass))

/* constants */

#endif /* IDL_TYPES_H */
